// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4gBQE81MaBhx_dsxWqHmLDyEs8G_-Yhc',
    appId: '1:631365223914:web:689356cce70b83edefde93',
    messagingSenderId: '631365223914',
    projectId: 'toko-fashion-cc521',
    authDomain: 'toko-fashion-cc521.firebaseapp.com',
    storageBucket: 'toko-fashion-cc521.firebasestorage.app',
    measurementId: 'G-3FRLYCV43V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwapH302bm2q6d8JI6GW17QNXOGz-FD1s',
    appId: '1:631365223914:android:b54774ec955338feefde93',
    messagingSenderId: '631365223914',
    projectId: 'toko-fashion-cc521',
    storageBucket: 'toko-fashion-cc521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbgeAdtIOovAFAZsk2OY4ne3Ggw6P-2uY',
    appId: '1:631365223914:ios:4cae9803f8e92f00efde93',
    messagingSenderId: '631365223914',
    projectId: 'toko-fashion-cc521',
    storageBucket: 'toko-fashion-cc521.firebasestorage.app',
    iosBundleId: 'com.example.fashionEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbgeAdtIOovAFAZsk2OY4ne3Ggw6P-2uY',
    appId: '1:631365223914:ios:4cae9803f8e92f00efde93',
    messagingSenderId: '631365223914',
    projectId: 'toko-fashion-cc521',
    storageBucket: 'toko-fashion-cc521.firebasestorage.app',
    iosBundleId: 'com.example.fashionEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4gBQE81MaBhx_dsxWqHmLDyEs8G_-Yhc',
    appId: '1:631365223914:web:1acb7a0798126180efde93',
    messagingSenderId: '631365223914',
    projectId: 'toko-fashion-cc521',
    authDomain: 'toko-fashion-cc521.firebaseapp.com',
    storageBucket: 'toko-fashion-cc521.firebasestorage.app',
    measurementId: 'G-VLZGMZWHZP',
  );
}
